services:
  # Spring Boot приложение
  evaluation-360-backend:
    image: evaluation-360-backend:v1.0
    container_name: evaluation-360-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/evaluation360
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongoadmin:mongopass@mongodb:27017/evaluation360?authSource=admin
    networks:
      - 360-backend
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres-360
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evaluation360
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - 360-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb-360
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: evaluation360
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - 360-backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

# Сети и тома
networks:
  360-backend:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data: