# Profile
spring.application.name=evaluation-360

# Server config
server.servlet.context-path=/api/v1
server.port=8080

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/evaluation-360-postgresql
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# MongoDB config
spring.data.mongodb.uri=mongodb://localhost:27017/evaluation-360-mongodb

# Admin config
adminstrator.config.email=${ADMIN_EMAIL}
adminstrator.config.password=${ADMIN_PASSWORD}

# Swagger config
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.csrf.cookie-name=XSRF-TOKEN
springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN
springdoc.swagger-ui.csrf.use-cookie=true

# Security config
spring.security.filter.order=10
spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC

# JWT config
jwt.secret.token=${JWT_SECRET}
jwt.time.live=360000
jwt.refresh.time.live=86400000